from pydantic import BaseModel

class CustomerModel(BaseModel):
    ID: int
    Year_Birth: int
    Education: str
    Marital_Status: str
    Income: float
    Kidhome: int
    Teenhome: int
    Dt_Customer: str
    Recency: int
    MntWines: int
    MntFruits: int
    MntMeatProducts: int
    MntFishProducts: int
    MntSweetProducts: int
    MntGoldProds: int
    NumDealsPurchases: int
    NumWebPurchases: int
    NumCatalogPurchases: int
    NumStorePurchases: int
    NumWebVisitsMonth: int
    AcceptedCmp3: int
    AcceptedCmp4: int
    AcceptedCmp5: int
    AcceptedCmp1: int
    AcceptedCmp2: int
    Complain: int
    Z_CostContact: int
    Z_Revenue: int
    Response: int